version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: programwithgio-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: programwithgio-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: programwithgio-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  mailhog:
    container_name: programwithgio-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
  cron:
    container_name: programwithgio-cron
    build: ./cron
    volumes:
      - ../src:/var/www
      - ./log/cron:/var/log/cron
  db2:
    container_name: programwithgio-db2
    image: mysql:8.0
    volumes:
      - ./storage/mysql2:/var/lib/mysql  # Change the volume path to your preference
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Change the password if needed
    ports:
      - 3308:3306